#+TITLE: Shelltest Mode

This package implements a major mode for [[http://joyful.com/shelltestrunner][shelltestrunner]].

Besides syntax highlighting, a few useful functions for dealing with
test files are provided.  These functions work from all modes and can
be bound to keys for additional convenience.

** Installation

TODO: write instructions

To load ~shelltest-mode~ for all *.test files, add the following to your
Emacs init file:

#+BEGIN_SRC emacs-lisp
(add-to-list 'auto-mode-alist '("\\.test\\'" . shelltest-mode))
#+END_SRC

** Functions

*** shelltest-find

Edit the test file that corresponds to the currently edited file.

The opened file is [[#shelltest-directory][shelltest-directory]]/file.test, where "file" is the
name of the currently edited file with its extension removed.
If [[#shelltest-other-window][shelltest-other-window]] is non-nil, open the file in another window.

*** shelltest-run

Run the test file associated with the currently edited file.

The command to be run is determined by [[#shelltest-command][shelltest-command]].  Its argument
is [[#shelltest-directory][shelltest-directory]]/file.test, where "file" is the name of the
currently edited file with its extension removed.

*** shelltest-run-all

Run all test files.

The command to be run is determined by [[#shelltest-command][shelltest-command]]. Its argument
is [[#shelltest-directory][shelltest-directory]].

** Customization

*** shelltest-other-window

/Default:/ ~t~

If given a non-nil value, [[#shelltest-find][shelltest-find]] uses another window.

*** shelltest-command

/Default:/ ~​"shelltest --execdir"​~

The command that [[#shelltest-run][shelltest-run]] and [[#shelltest-run-all][shelltest-run-all]] execute.

*** shelltest-directory

/Default:/ ~​"./tests"​~

The directory in which the test files are located.
